
services:
  mysql:
    image: mysql:8.4
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
      - "./src/main/resources/db/mysql:/docker-entrypoint-initdb.d/"  # Mount the SQL script directory
      - "mysql-data:/var/lib/mysql"
    networks:
      - petclinic-network5
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 10
      timeout: 5s

  app:
    #image: app:copy2
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petclinic-app
    environment:
      MYSQL_URL: jdbc:mysql://mysql_db:3306/petclinic
      SPRING_DATASOURCE_USERNAME: petclinic
      SPRING_DATASOURCE_PASSWORD: petclinic
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - petclinic-network5

volumes:
  mysql-data:

networks:
  petclinic-network5:
    driver: bridge
