apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: actions-runner-system
  name: actions-runner-role
rules:
  - apiGroups: ["", "apps"]
    resources: ["deployments", "services", "persistentvolumeclaims"]
    verbs: ["get", "list", "watch", "create", "delete", "update"]