apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: actions-runner-rolebinding
  namespace: actions-runner-system
subjects:
  - kind: ServiceAccount
    name: default
    namespace: actions-runner-system
roleRef:
  kind: Role
  name: actions-runner-role
  apiGroup: rbac.authorization.k8s.io