
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: checkout-repo-with-list
spec:
  workspaces:
    - name: shared-workspace
  steps:
    - name: clean-workspace
      image: ubuntu
      script: |
        rm -rf $(workspaces.shared-workspace.path)/* $(workspaces.shared-workspace.path)/.[!.]* $(workspaces.shared-workspace.path)/..?*
    - name: git-clone
      image: alpine/git
      script: |
        git clone $(params.repo-url) $(workspaces.shared-workspace.path)
    - name: list-files
      image: ubuntu
      script: |
        ls -la $(workspaces.shared-workspace.path)/tekton/pipeline
  params:
    - name: repo-url
      type: string
      description: The git repository URL
