apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven-build
spec:
  description: |
    This task runs $mvn clean package to build the Spring Boot app.
  workspaces:
    - name: output  # This is the shared workspace containing the repo files
  steps:
    - name: maven-build-step
      image: maven:3.8.7-eclipse-temurin-17
      script: |
        #!/usr/bin/env sh
        cd $(workspaces.output.path)  # Navigate to the cloned repo directory
        mvn clean
        mvn spring-javaformat:apply
        mvn package  # Run the Maven build
      volumeMounts:
        - name: maven-repo-cache
          mountPath: /root/.m2/repository
  volumes:
    - name: maven-repo-cache
      persistentVolumeClaim:
        claimName: maven-repo-cache-pvc
