apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-init-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi  # Enough for initialization scripts
