apiVersion: v1
kind: Service
metadata:
  name: petclinic-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: petclinic-app
  type: LoadBalancer  # Adjust based on your Kubernetes environment (e.g., NodePort for Minikube)
