name: Login DockerHub

on:
  workflow_call:
    #inputs:
    #  DOCKER_IMAGE:
    #    required: true
    #    type: string
    #    description: "Nombre de la imagen Docker a publicar"
    #  IMAGE_TAG:
    #    required: true
    #   description: "Tag de la imagen Docker"
    #   type: string

    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      #- name: Build Docker Image
      #  run: |
      #    docker build -t ${{ inputs.DOCKER_IMAGE }}:${{ inputs.IMAGE_TAG }} .
        
      #- name: Push Docker Image
      #  run: |
      #    docker push ${{ inputs.DOCKER_IMAGE }}:${{ inputs.IMAGE_TAG }}